# The build manifest — Python's half of the one bench-wide bundle, assembled for vite.

# Everything here runs with no site: `bench build` calls `frappe.init("")`, so apps come
# from `get_all_apps()` and hooks from `get_hooks(app_name=)`.

import json
import os

import frappe

from .registry import declared_prefix

#: Enforced by the build and documented nowhere else; a duplicate instance breaks provide/inject.
SINGLETONS = ("vue", "vue-router", "frappe-ui", "@framework/ui", "reka-ui", "dompurify")

MANIFEST_FILENAME = "manifest.json"


class SingletonConflict(Exception):
	pass


def contribution_globs(source_dir: str) -> list[str]:
	"""The five contribution kinds, as paths; a file anywhere else is not a contribution."""
	return [
		os.path.join(source_dir, "*", "doctype", "*", "frontend", "record.js"),
		os.path.join(source_dir, "*", "doctype", "*", "frontend", "list.js"),
		os.path.join(source_dir, "*", "custom", "*", "record.js"),
		os.path.join(source_dir, "*", "frontend", "pages", "*.js"),
		# Beside the `Navigation Item Type` JSON, where the plugin reads the kind's real name.
		os.path.join(source_dir, "*", "navigation_item_type", "*", "frontend", "item.js"),
	]


def contributes(source_dir: str) -> bool:
	import glob

	return any(glob.glob(pattern) for pattern in contribution_globs(source_dir))


def read_package(path: str) -> dict:
	if not os.path.exists(path):
		return {}
	# Bench-internal path, composed from `get_app_path`; never request-derived.
	with open(path) as f:  # nosemgrep
		return json.load(f)


def app_deps(app: str) -> dict[str, str]:
	"""The app's own declared dependencies, dev included."""
	# frappe's own declaration is `frontend/package.base.json`; `frappe/package.json` is desk v1's
	# esbuild stack, a different bundle with different pins.
	if app == "frappe":
		package = read_package(os.path.join(frontend_dir(), "package.base.json"))
	else:
		package = read_package(os.path.join(frappe.get_app_path(app, ".."), "package.json"))

	return {**package.get("dependencies", {}), **package.get("devDependencies", {})}


def app_runtime_deps(app: str) -> dict[str, str]:
	"""Only what contributed source can import: `dependencies`, never `devDependencies`."""
	if app == "frappe":
		package = read_package(os.path.join(frontend_dir(), "package.base.json"))
	else:
		package = read_package(os.path.join(frappe.get_app_path(app, ".."), "package.json"))

	return package.get("dependencies", {})


def frontend_dir() -> str:
	return os.path.join(frappe.get_app_source_path("frappe"), "frontend")


def assemble() -> list[dict]:
	"""The manifest in `sites/apps.txt` order: frappe, plus every app that contributes source."""
	manifest = []

	for app in frappe.get_all_apps():
		try:
			source_dir = frappe.get_app_path(app)
		except Exception as e:
			# Fail naming the app: a silently skipped app is a prefix that silently stops resolving.
			raise RuntimeError(f"Could not locate source for app '{app}': {e}") from e

		if app != "frappe" and not contributes(source_dir):
			continue

		manifest.append(
			{
				"app": app,
				"app_prefix": declared_prefix(app),
				"source_dir": source_dir,
				"deps": app_deps(app),
				"runtime_deps": app_runtime_deps(app),
			}
		)

	return manifest


def enforce_singletons(manifest: list[dict]):
	"""Fail the build when two apps in the bundle disagree on a shared library."""
	# Before vite starts, and not `resolve.dedupe`, which silently picks a winner.
	claims: dict[str, list[tuple[str, str]]] = {}

	for entry in manifest:
		for package in SINGLETONS:
			if declared := entry["deps"].get(package):
				claims.setdefault(package, []).append((entry["app"], declared))

	conflicts = []
	for package, declarations in claims.items():
		ranges = {declared for _app, declared in declarations}
		if len(ranges) > 1:
			named = ", ".join(f"{app} wants {declared}" for app, declared in sorted(declarations))
			conflicts.append(f"  {package}: {named}")

	if conflicts:
		raise SingletonConflict(
			"The desk shell builds one module graph, which admits one version of each "
			"shared library. These are declared at conflicting versions:\n"
			+ "\n".join(conflicts)
			+ "\n\nAlign the ranges in the apps' package.json files and build again."
		)


def compose_package_json(manifest: list[dict], frontend: str) -> bool:
	"""The one tree yarn installs: the framework's pins plus every app's own deps, generated."""
	# `package.base.json` always wins, so an app cannot move a singleton by naming it.
	base = read_package(os.path.join(frontend, "package.base.json"))
	dependencies = dict(base.get("dependencies", {}))

	for entry in manifest:
		if entry["app"] == "frappe":
			continue
		for package, declared in entry["runtime_deps"].items():
			if package in SINGLETONS or package in dependencies:
				continue
			dependencies[package] = declared

	composed = {
		**base,
		"comment": "GENERATED by frappe/shell/manifest.py from package.base.json. Do not edit.",
		"dependencies": dependencies,
	}

	path = os.path.join(frontend, "package.json")
	# A rewritten file with identical contents must not trigger a reinstall.
	changed = read_package(path).get("dependencies") != dependencies

	# Bench-internal path, composed from `frontend_dir()`; never request-derived.
	with open(path, "w") as f:  # nosemgrep
		json.dump(composed, f, indent=2)

	return changed


def write(frontend: str | None = None) -> bool:
	"""Assemble, enforce, write the manifest; returns whether the dependency set changed."""
	frontend = frontend or frontend_dir()
	manifest = assemble()
	enforce_singletons(manifest)

	# `source_dirs` is every app, not just contributors: a `custom/` folder may name a doctype
	# owned by an app that contributes nothing. Bench-internal path; never request-derived.
	with open(os.path.join(frontend, MANIFEST_FILENAME), "w") as f:  # nosemgrep
		json.dump(
			{
				"apps": manifest,
				"source_dirs": [frappe.get_app_path(app) for app in frappe.get_all_apps()],
			},
			f,
			indent="\t",
		)

	return compose_package_json(manifest, frontend)
