"""Generate `{app}/doctypes.py` and `{app}/doctypes.pyi` for an app.

`doctypes.py` exposes every DocType controller as a lazy proxy so that
`from frappe.doctypes import User` works without eagerly importing the
controller module. `doctypes.pyi` mirrors the same names with real imports so
type checkers and IDEs resolve them to the actual controller class.
"""

from __future__ import annotations

import json
from pathlib import Path

HEADER = (
	"# This file is auto-generated by `bench generate-doctype-imports`. Do not edit.\n"
	"# Run the command again after adding, removing, or renaming a DocType.\n"
)


def _iter_doctypes(app_path: Path):
	"""Yield (class_name, controller_module) for every standard DocType under `app_path`."""
	for json_path in app_path.rglob("doctype/*/*.json"):
		name = json_path.stem
		if json_path.parent.name != name:
			continue
		py_path = json_path.with_suffix(".py")
		if not py_path.exists():
			continue
		try:
			with json_path.open() as f:
				data = json.load(f)
		except (OSError, ValueError):
			continue
		if data.get("doctype") != "DocType":
			continue
		doctype_name = data.get("name")
		if not doctype_name:
			continue
		class_name = doctype_name.replace(" ", "").replace("-", "")
		rel = py_path.relative_to(app_path.parent).with_suffix("")
		module = ".".join(rel.parts)
		yield class_name, module


def generate(app: str) -> tuple[Path, Path]:
	"""Generate `{app}/doctypes.py` and `{app}/doctypes.pyi`. Return their paths."""
	import frappe

	app_path = Path(frappe.get_app_path(app))
	entries = sorted(set(_iter_doctypes(app_path)))

	py_path = app_path / "doctypes.py"
	pyi_path = app_path / "doctypes.pyi"

	py = [HEADER]
	py.append(
		f'"""Lazy DocType controller imports for `{app}`.\n\n'
		"Importing a name here does NOT load the controller module; the module is\n"
		"imported on first real use (instantiation, attribute access, isinstance).\n"
		'"""\n\n'
	)
	py.append("from frappe.utils.lazy_controller import make_lazy_controller\n\n")
	py.append("_DOCTYPES = {\n")
	for class_name, module in entries:
		py.append(f'\t"{class_name}": "{module}",\n')
	py.append("}\n\n\n")
	py.append(
		"def __getattr__(name):\n"
		"\ttry:\n"
		"\t\tmodule_path = _DOCTYPES[name]\n"
		"\texcept KeyError:\n"
		'\t\traise AttributeError(f"module {__name__!r} has no attribute {name!r}") from None\n'
		"\tcls = make_lazy_controller(name, module_path, name, defined_in=__name__)\n"
		"\tglobals()[name] = cls\n"
		"\treturn cls\n"
		"\n\n"
		"def __dir__():\n"
		"\treturn list(_DOCTYPES)\n"
	)

	pyi = [HEADER, "\n"]
	for class_name, module in entries:
		pyi.append(f"from {module} import {class_name} as {class_name}\n")

	py_path.write_text("".join(py))
	pyi_path.write_text("".join(pyi))
	return py_path, pyi_path
