import frappe
from frappe import _
from frappe.utils.caching import redis_cache


def get_module_placement(module: str) -> str | None:
	"""The app whose dock lists `module`, or `None` when it is unplaced.

	Placement, never ownership. An app's own module is placed in it because the app declared
	it in `modules.txt`; a site's custom module is placed by `Module Def.app_name`, which for
	a custom module is a hint meaning *"list this in that app's dock"* and may be empty.

	`None` is therefore an ordinary answer rather than an error, and that is the difference
	from `frappe.get_module_app`: that one resolves a module to a **path on disk** and is
	right to throw when there is none, since a custom module has no folder. Asking it the
	navigation question is what used to leave a freshly created custom module invisible --
	the throw was swallowed and the module was skipped.
	"""
	app = frappe.local.module_app.get(frappe.scrub(module))
	return app or frappe.db.get_value("Module Def", module, "app_name") or None


def get_blocked_modules(user: str | None = None) -> list[str]:
	"""Modules hidden from `user`, i.e. their own `User.block_modules`.

	This is the module-level access gate the desk applies wherever a module -- rather than a
	document -- is what's being shown: the module view, module-scoped dashboards/cards, a
	workspace that falls back to its module for visibility (`Workspace.is_permitted`), and the
	autogenerated module sidebars in the boot payload.

	`user`'s own list is the whole list. Blocking a module on `Administrator` used to be unioned
	in here as a site-wide block, which made a per-user preference field double as site config
	with no UI saying so: nothing on the User form marks the Administrator row as the global one,
	and a module blocked there was unhideable for every other user. Site-wide module visibility
	belongs in the app/module setup, not in one user's preference table -- so this reads only
	`user`. Don't reintroduce the Administrator union.
	"""
	user = user or frappe.session.user
	return frappe.get_cached_doc("User", user).get_blocked_modules()


def is_module_visible(module: str | None, user: str | None = None) -> bool:
	"""Whether `module` may appear in `user`'s desk navigation.

	    visible(m, u) = m not in blocked(u)

	**Navigation reach only. Never call this from `has_permission`.** Document access is
	decided by DocPerm, and routing it through here would turn a navigation preference into a
	security boundary. Hiding a module hides the way *to* a document, never the document itself.
	"""
	if not module:
		return True

	return module not in get_blocked_modules(user)


def get_visible_modules(modules: list[str], user: str | None = None) -> list[str]:
	"""Batched `is_module_visible`, for callers filtering a whole list at once."""
	blocked = set(get_blocked_modules(user))

	return [m for m in modules if m not in blocked]


def get_code_only_modules() -> set[str]:
	"""Modules their own app says ship no navigation.

	A module is two things at once -- a folder of code and a place in the dock -- and an app
	splitting its navigation into semantic modules is left holding the first without wanting the
	second. `frappe.Core` is the case this exists for: its doctypes, reports and pages stay put
	while `System`, `Build Tools`, `Data` and `Users` carry the navigation, and without this it
	would keep a dock entry whose computed base is the leftover grab-bag of everything nobody
	moved.

	Declared in `hooks.py` (`code_only_modules`), so it travels with the app that made the split
	rather than being site state somebody has to re-apply -- and an existing site gets it on the
	next boot with no patch to run.

	**Not a permission gate, and deliberately not part of `is_module_visible`.** That one decides
	whether a module's *contents* may be reached -- `Workspace.is_permitted` falls back to it, as
	do the module-scoped chart and card pickers -- so folding this in would make Core's workspaces
	and dashboard records unreachable rather than merely unlisted. This is only about the dock;
	see `frappe.boot.get_navigable_modules`, its one caller.

	Uncached on purpose: `get_hooks` already caches the merged hook map per site and busts it on
	migrate, so a second cache here would only add a copy nothing invalidates.
	"""
	return set(frappe.get_hooks("code_only_modules") or [])


def get_modules_from_all_apps_for_user(user: str | None = None) -> list[dict]:
	user = user or frappe.session.user
	all_modules = get_modules_from_all_apps()
	visible = set(get_visible_modules([m.get("module_name") for m in all_modules], user))

	return [m for m in all_modules if m.get("module_name") in visible]


def get_modules_from_all_apps():
	modules_list = []
	for app in frappe.get_active_apps():
		modules_list += get_modules_from_app(app)
	return modules_list


@redis_cache
def get_modules_from_app(app):
	return frappe.get_all("Module Def", filters={"app_name": app}, fields=["module_name", "app_name as app"])


def is_domain(module):
	return module.get("category") == "Domains"


def is_module(module):
	return module.get("type") == "module"
