import frappe
from frappe import _
from frappe.utils.caching import redis_cache


def get_blocked_modules(user: str | None = None) -> list[str]:
	"""Modules hidden from `user`, i.e. their own `User.block_modules`.

	This is the module-level access gate the desk applies wherever a module -- rather than a
	document -- is what's being shown: the module view, module-scoped dashboards/cards, a
	workspace that falls back to its module for visibility (`Workspace.is_permitted`), and the
	autogenerated module sidebars in the boot payload.

	`user`'s own list is the whole list. Blocking a module on `Administrator` used to be unioned
	in here as a site-wide block, which made a per-user preference field double as site config
	with no UI saying so: nothing on the User form marks the Administrator row as the global one,
	and a module blocked there was unhideable for every other user. Site-wide module visibility
	belongs in the app/module setup, not in one user's preference table -- so this reads only
	`user`. Don't reintroduce the Administrator union.
	"""
	user = user or frappe.session.user
	return frappe.get_cached_doc("User", user).get_blocked_modules()


def get_modules_from_all_apps_for_user(user: str | None = None) -> list[dict]:
	user = user or frappe.session.user
	all_modules = get_modules_from_all_apps()
	blocked_modules = get_blocked_modules(user)
	allowed_modules_list = [m for m in all_modules if m.get("module_name") not in blocked_modules]

	return allowed_modules_list


def get_modules_from_all_apps():
	modules_list = []
	for app in frappe.get_active_apps():
		modules_list += get_modules_from_app(app)
	return modules_list


@redis_cache
def get_modules_from_app(app):
	return frappe.get_all("Module Def", filters={"app_name": app}, fields=["module_name", "app_name as app"])


def is_domain(module):
	return module.get("category") == "Domains"


def is_module(module):
	return module.get("type") == "module"
