import frappe
from frappe import _
from frappe.utils.caching import redis_cache


def get_blocked_modules(user: str | None = None) -> list[str]:
	"""Modules hidden from `user`, i.e. their own `User.block_modules`.

	This is the module-level access gate the desk applies wherever a module -- rather than a
	document -- is what's being shown: the module view, module-scoped dashboards/cards, a
	workspace that falls back to its module for visibility (`Workspace.is_permitted`), and the
	autogenerated module sidebars in the boot payload.

	`user`'s own list is the whole list. Blocking a module on `Administrator` used to be unioned
	in here as a site-wide block, which made a per-user preference field double as site config
	with no UI saying so: nothing on the User form marks the Administrator row as the global one,
	and a module blocked there was unhideable for every other user. Site-wide module visibility
	belongs in the app/module setup, not in one user's preference table -- so this reads only
	`user`. Don't reintroduce the Administrator union.
	"""
	user = user or frappe.session.user
	return frappe.get_cached_doc("User", user).get_blocked_modules()


MODULE_GRANT_CACHE_KEY = "governed_modules"


@redis_cache
def get_governed_modules() -> set[str]:
	"""Modules that at least one Role explicitly grants.

	A module no Role names is *ungoverned* and stays visible to everyone. That is what makes
	this safe to switch on: on an existing site no Role has any modules, so nothing is
	governed and visibility is unchanged.
	"""
	return set(frappe.get_all("Role Module", pluck="module", distinct=True))


def get_granted_modules(user: str | None = None) -> set[str]:
	"""Modules granted to `user` by the roles they hold."""
	roles = frappe.get_roles(user or frappe.session.user)
	if not roles:
		return set()
	return set(
		frappe.get_all("Role Module", filters={"parent": ["in", roles]}, pluck="module", distinct=True)
	)


def is_module_visible(module: str | None, user: str | None = None) -> bool:
	"""Whether `module` may appear in `user`'s desk navigation.

	    visible(m, u) = m not in blocked(u)                          # deny wins
	                and (m not in governed() or m in granted(u))     # ungoverned = open to all

	**Navigation reach only. Never call this from `has_permission`.** Document access is
	decided by DocPerm, and routing it through here would turn a navigation preference into a
	security boundary -- one that a user could widen by acquiring any role that grants the
	module. Hiding a module hides the way *to* a document, never the document itself.
	"""
	if not module:
		return True

	if module in get_blocked_modules(user):
		return False

	governed = get_governed_modules()
	if module not in governed:
		return True

	return module in get_granted_modules(user)


def get_visible_modules(modules: list[str], user: str | None = None) -> list[str]:
	"""Batched `is_module_visible`, for callers filtering a whole list at once."""
	blocked = set(get_blocked_modules(user))
	governed = get_governed_modules()
	granted = get_granted_modules(user) if governed else set()

	return [m for m in modules if m not in blocked and (m not in governed or m in granted)]


def clear_module_permission_cache():
	"""Bust the governed-module set. Called whenever a Role's modules table changes."""
	get_governed_modules.clear_cache()


def get_modules_from_all_apps_for_user(user: str | None = None) -> list[dict]:
	user = user or frappe.session.user
	all_modules = get_modules_from_all_apps()
	visible = set(get_visible_modules([m.get("module_name") for m in all_modules], user))

	return [m for m in all_modules if m.get("module_name") in visible]


def get_modules_from_all_apps():
	modules_list = []
	for app in frappe.get_active_apps():
		modules_list += get_modules_from_app(app)
	return modules_list


@redis_cache
def get_modules_from_app(app):
	return frappe.get_all("Module Def", filters={"app_name": app}, fields=["module_name", "app_name as app"])


def is_domain(module):
	return module.get("category") == "Domains"


def is_module(module):
	return module.get("type") == "module"
