// The app's island Tailwind config. One config for all of an app's islands,
// because they share one stylesheet.

import fs from "node:fs";
import path from "node:path";

/** Generated configs live where every other build artifact does. */
const CONFIG_DIR = "node_modules/.island";

/**
 * Write the island Tailwind config and return its path.
 *
 * The preset writes a file instead of passing a config object, because only
 * Tailwind's own config loader resolves `tailwindcss/plugin`. Tailwind 3
 * publishes no `exports` entry for that subpath, and `frappe-ui/tailwind` is ESM
 * that imports it. Plugins arrive as module specifiers for the same reason. The
 * file sits in the app's `node_modules`, so a bare specifier resolves against
 * the app's own dependencies.
 *
 * `content` is the bundle's module list, not a glob the app keeps. See
 * `discoverSources` in ./index.js.
 *
 * @param {Object} context  from `islandContext`
 * @param {string[]} sources  absolute paths of the files to scan
 * @returns {string} the config's path
 */
export function writeIslandTailwindConfig(context, sources) {
	const { root, app, tailwindPlugins = [] } = context;
	const dir = path.join(root, CONFIG_DIR);
	const configPath = path.join(dir, `tailwind.${app}.config.mjs`);
	const pluginNames = tailwindPlugins.map((_, index) => `plugin${index}`);

	fs.mkdirSync(dir, { recursive: true });
	fs.writeFileSync(
		configPath,
		[
			"// Generated by @framework/ui/vite/island. Do not edit.",
			'import preset from "frappe-ui/tailwind";',
			...tailwindPlugins.map(
				(specifier, index) =>
					`import ${pluginNames[index]} from ${JSON.stringify(specifier)};`
			),
			"",
			"export default {",
			"	presets: [preset],",
			// The shadow root holds one theme container, and the island's own
			// `dark:` utilities flip on the attribute the mount contract sets.
			'	darkMode: ["selector", \'[data-theme="dark"]\'],',
			`	content: ${JSON.stringify(sources, null, 1).replace(/\n/g, "\n\t")},`,
			// The app's own plugins. Without them its `@container` and the like
			// compile to nothing here, while they work in its SPA build.
			`	plugins: [${pluginNames.join(", ")}],`,
			"	theme: { extend: {} },",
			"};",
			"",
		].join("\n")
	);

	return configPath;
}
