// The build tooling, resolved from the app.
//
// This preset ships as source inside `@framework/ui`, which a bench links by
// relative path. Node resolves a bare specifier from a module's real path, so an
// `import "vite"` here would look beside the framework checkout. A bench never
// installs a frontend's dependencies there. The app is the one place where
// Vite, Tailwind and frappe-ui are installed, so the preset resolves every
// build-time dependency from there.
// ../../../island/decisions/0005-the-preset-resolves-its-tooling-from-the-app.md

import fs from "node:fs";
import path from "node:path";
import { pathToFileURL } from "node:url";

/** Every module the preset needs from the app's own tree. */
const TOOLS = {
	vite: "vite",
	vue: "@vitejs/plugin-vue",
	tailwindcss: "tailwindcss",
	autoprefixer: "autoprefixer",
	lucideIcons: "frappe-ui/vite/lucideIconsPlugin",
	compilerSfc: "vue/compiler-sfc",
	typescript: "typescript",
};

/** Generated modules live where every other build artifact does. */
const GENERATED_DIR = "node_modules/.island";

/**
 * Load the preset's build tooling out of the app at `root`.
 *
 * The preset writes a module into the app's `node_modules` and imports that,
 * instead of resolving each specifier itself. A bare import inside the written
 * file resolves against the app's dependencies, through Node's own resolver and
 * its `import` condition. To resolve from here instead, the preset would
 * re-implement that. `require.resolve` reads the `require` condition, and it
 * refuses an ESM-only subpath such as `frappe-ui/vite/lucideIconsPlugin`.
 *
 * @param {string} root  the app's frontend directory
 * @returns {Promise<Object>}  one loaded module per key of `TOOLS`
 */
export async function loadTools(root) {
	const file = path.join(root, GENERATED_DIR, "tools.mjs");

	fs.mkdirSync(path.dirname(file), { recursive: true });
	fs.writeFileSync(
		file,
		[
			"// Generated by @framework/ui/vite/island. Do not edit.",
			...Object.entries(TOOLS).map(
				([key, specifier]) => `export * as ${key} from ${JSON.stringify(specifier)};`
			),
			"",
		].join("\n")
	);

	let tools;
	try {
		tools = await import(pathToFileURL(file).href);
	} catch (error) {
		throw new Error(
			`island: the build tooling does not resolve from ${root}: ` +
				`${error.message}\nThe island build runs on the app's own ` +
				"tooling, so the app has to depend on it. Add the missing " +
				"package to the frontend's devDependencies."
		);
	}

	registerTypeScript(tools);
	return tools;
}

/**
 * `module.exports`, out of a dynamically imported CommonJS module.
 *
 * Tailwind, autoprefixer and compiler-sfc are CommonJS. A static
 * `import x from "tailwindcss"` binds `module.exports` to `x`. A namespace
 * import answers with the namespace instead, and puts `module.exports` on its
 * `default`.
 */
export const interop = (module) => module.default ?? module;

/**
 * Give compiler-sfc a TypeScript, so it can resolve a prop type imported from
 * another package.
 *
 * frappe-ui's `ImageGroupNodeView.vue` writes `defineProps<NodeViewProps>()`
 * against a type from `@tiptap/vue-3`. compiler-sfc resolves that only through
 * the TypeScript compiler API, and @vitejs/plugin-vue registers no compiler. The
 * version must be TS >= 5: the types sit behind `exports` maps that only
 * `moduleResolution: bundler` can follow.
 */
function registerTypeScript({ compilerSfc, typescript }) {
	interop(compilerSfc).registerTS(() => interop(typescript));
}
