# This file is auto-generated by `bench generate-doctype-imports`. Do not edit.
# Run the command again after adding, removing, or renaming a DocType.

from frappe.automation.doctype.assignment_rule.assignment_rule import AssignmentRule as AssignmentRule
from frappe.automation.doctype.assignment_rule_day.assignment_rule_day import (
	AssignmentRuleDay as AssignmentRuleDay,
)
from frappe.automation.doctype.assignment_rule_user.assignment_rule_user import (
	AssignmentRuleUser as AssignmentRuleUser,
)
from frappe.automation.doctype.auto_repeat.auto_repeat import AutoRepeat as AutoRepeat
from frappe.automation.doctype.auto_repeat_day.auto_repeat_day import AutoRepeatDay as AutoRepeatDay
from frappe.automation.doctype.auto_repeat_user.auto_repeat_user import AutoRepeatUser as AutoRepeatUser
from frappe.automation.doctype.milestone.milestone import Milestone as Milestone
from frappe.automation.doctype.milestone_tracker.milestone_tracker import MilestoneTracker as MilestoneTracker
from frappe.automation.doctype.reminder.reminder import Reminder as Reminder
from frappe.contacts.doctype.address.address import Address as Address
from frappe.contacts.doctype.address_template.address_template import AddressTemplate as AddressTemplate
from frappe.contacts.doctype.contact.contact import Contact as Contact
from frappe.contacts.doctype.contact_email.contact_email import ContactEmail as ContactEmail
from frappe.contacts.doctype.contact_phone.contact_phone import ContactPhone as ContactPhone
from frappe.contacts.doctype.gender.gender import Gender as Gender
from frappe.contacts.doctype.salutation.salutation import Salutation as Salutation
from frappe.core.doctype.access_log.access_log import AccessLog as AccessLog
from frappe.core.doctype.activity_log.activity_log import ActivityLog as ActivityLog
from frappe.core.doctype.amended_document_naming_settings.amended_document_naming_settings import (
	AmendedDocumentNamingSettings as AmendedDocumentNamingSettings,
)
from frappe.core.doctype.api_request_log.api_request_log import APIRequestLog as APIRequestLog
from frappe.core.doctype.audit_trail.audit_trail import AuditTrail as AuditTrail
from frappe.core.doctype.background_task.background_task import BackgroundTask as BackgroundTask
from frappe.core.doctype.block_module.block_module import BlockModule as BlockModule
from frappe.core.doctype.comment.comment import Comment as Comment
from frappe.core.doctype.communication.communication import Communication as Communication
from frappe.core.doctype.communication_link.communication_link import CommunicationLink as CommunicationLink
from frappe.core.doctype.custom_docperm.custom_docperm import CustomDocPerm as CustomDocPerm
from frappe.core.doctype.custom_role.custom_role import CustomRole as CustomRole
from frappe.core.doctype.data_export.data_export import DataExport as DataExport
from frappe.core.doctype.data_import.data_import import DataImport as DataImport
from frappe.core.doctype.data_import_log.data_import_log import DataImportLog as DataImportLog
from frappe.core.doctype.defaultvalue.defaultvalue import DefaultValue as DefaultValue
from frappe.core.doctype.deleted_document.deleted_document import DeletedDocument as DeletedDocument
from frappe.core.doctype.docfield.docfield import DocField as DocField
from frappe.core.doctype.docperm.docperm import DocPerm as DocPerm
from frappe.core.doctype.docshare.docshare import DocShare as DocShare
from frappe.core.doctype.doctype.doctype import DocType as DocType
from frappe.core.doctype.doctype_action.doctype_action import DocTypeAction as DocTypeAction
from frappe.core.doctype.doctype_link.doctype_link import DocTypeLink as DocTypeLink
from frappe.core.doctype.doctype_state.doctype_state import DocTypeState as DocTypeState
from frappe.core.doctype.document_naming_rule.document_naming_rule import (
	DocumentNamingRule as DocumentNamingRule,
)
from frappe.core.doctype.document_naming_rule_condition.document_naming_rule_condition import (
	DocumentNamingRuleCondition as DocumentNamingRuleCondition,
)
from frappe.core.doctype.document_naming_settings.document_naming_settings import (
	DocumentNamingSettings as DocumentNamingSettings,
)
from frappe.core.doctype.document_share_key.document_share_key import DocumentShareKey as DocumentShareKey
from frappe.core.doctype.domain.domain import Domain as Domain
from frappe.core.doctype.domain_settings.domain_settings import DomainSettings as DomainSettings
from frappe.core.doctype.dynamic_link.dynamic_link import DynamicLink as DynamicLink
from frappe.core.doctype.error_log.error_log import ErrorLog as ErrorLog
from frappe.core.doctype.file.file import File as File
from frappe.core.doctype.has_domain.has_domain import HasDomain as HasDomain
from frappe.core.doctype.has_role.has_role import HasRole as HasRole
from frappe.core.doctype.installed_application.installed_application import (
	InstalledApplication as InstalledApplication,
)
from frappe.core.doctype.installed_applications.installed_applications import (
	InstalledApplications as InstalledApplications,
)
from frappe.core.doctype.language.language import Language as Language
from frappe.core.doctype.log_setting_user.log_setting_user import LogSettingUser as LogSettingUser
from frappe.core.doctype.log_settings.log_settings import LogSettings as LogSettings
from frappe.core.doctype.logs_to_clear.logs_to_clear import LogsToClear as LogsToClear
from frappe.core.doctype.module_def.module_def import ModuleDef as ModuleDef
from frappe.core.doctype.module_profile.module_profile import ModuleProfile as ModuleProfile
from frappe.core.doctype.navbar_item.navbar_item import NavbarItem as NavbarItem
from frappe.core.doctype.navbar_settings.navbar_settings import NavbarSettings as NavbarSettings
from frappe.core.doctype.package.package import Package as Package
from frappe.core.doctype.package_import.package_import import PackageImport as PackageImport
from frappe.core.doctype.package_release.package_release import PackageRelease as PackageRelease
from frappe.core.doctype.page.page import Page as Page
from frappe.core.doctype.patch_log.patch_log import PatchLog as PatchLog
from frappe.core.doctype.permission_inspector.permission_inspector import (
	PermissionInspector as PermissionInspector,
)
from frappe.core.doctype.permission_log.permission_log import PermissionLog as PermissionLog
from frappe.core.doctype.permission_type.permission_type import PermissionType as PermissionType
from frappe.core.doctype.prepared_report.prepared_report import PreparedReport as PreparedReport
from frappe.core.doctype.recorder.recorder import Recorder as Recorder
from frappe.core.doctype.recorder_query.recorder_query import RecorderQuery as RecorderQuery
from frappe.core.doctype.recorder_suggested_index.recorder_suggested_index import (
	RecorderSuggestedIndex as RecorderSuggestedIndex,
)
from frappe.core.doctype.report.report import Report as Report
from frappe.core.doctype.report_column.report_column import ReportColumn as ReportColumn
from frappe.core.doctype.report_filter.report_filter import ReportFilter as ReportFilter
from frappe.core.doctype.role.role import Role as Role
from frappe.core.doctype.role_permission_for_page_and_report.role_permission_for_page_and_report import (
	RolePermissionforPageandReport as RolePermissionforPageandReport,
)
from frappe.core.doctype.role_profile.role_profile import RoleProfile as RoleProfile
from frappe.core.doctype.rq_job.rq_job import RQJob as RQJob
from frappe.core.doctype.rq_worker.rq_worker import RQWorker as RQWorker
from frappe.core.doctype.scheduled_job_log.scheduled_job_log import ScheduledJobLog as ScheduledJobLog
from frappe.core.doctype.scheduled_job_type.scheduled_job_type import ScheduledJobType as ScheduledJobType
from frappe.core.doctype.scheduler_event.scheduler_event import SchedulerEvent as SchedulerEvent
from frappe.core.doctype.security_settings.security_settings import SecuritySettings as SecuritySettings
from frappe.core.doctype.security_settings_contact.security_settings_contact import (
	SecuritySettingsContact as SecuritySettingsContact,
)
from frappe.core.doctype.security_settings_language.security_settings_language import (
	SecuritySettingsLanguage as SecuritySettingsLanguage,
)
from frappe.core.doctype.server_script.server_script import ServerScript as ServerScript
from frappe.core.doctype.session_default.session_default import SessionDefault as SessionDefault
from frappe.core.doctype.session_default_settings.session_default_settings import (
	SessionDefaultSettings as SessionDefaultSettings,
)
from frappe.core.doctype.sms_log.sms_log import SMSLog as SMSLog
from frappe.core.doctype.sms_parameter.sms_parameter import SMSParameter as SMSParameter
from frappe.core.doctype.sms_settings.sms_settings import SMSSettings as SMSSettings
from frappe.core.doctype.submission_queue.submission_queue import SubmissionQueue as SubmissionQueue
from frappe.core.doctype.success_action.success_action import SuccessAction as SuccessAction
from frappe.core.doctype.system_settings.system_settings import SystemSettings as SystemSettings
from frappe.core.doctype.translation.translation import Translation as Translation
from frappe.core.doctype.user.user import User as User
from frappe.core.doctype.user_document_type.user_document_type import UserDocumentType as UserDocumentType
from frappe.core.doctype.user_email.user_email import UserEmail as UserEmail
from frappe.core.doctype.user_group.user_group import UserGroup as UserGroup
from frappe.core.doctype.user_group_member.user_group_member import UserGroupMember as UserGroupMember
from frappe.core.doctype.user_invitation.user_invitation import UserInvitation as UserInvitation
from frappe.core.doctype.user_permission.user_permission import UserPermission as UserPermission
from frappe.core.doctype.user_role.user_role import UserRole as UserRole
from frappe.core.doctype.user_role_profile.user_role_profile import UserRoleProfile as UserRoleProfile
from frappe.core.doctype.user_select_document_type.user_select_document_type import (
	UserSelectDocumentType as UserSelectDocumentType,
)
from frappe.core.doctype.user_session_display.user_session_display import (
	UserSessionDisplay as UserSessionDisplay,
)
from frappe.core.doctype.user_social_login.user_social_login import UserSocialLogin as UserSocialLogin
from frappe.core.doctype.user_type.user_type import UserType as UserType
from frappe.core.doctype.user_type_module.user_type_module import UserTypeModule as UserTypeModule
from frappe.core.doctype.version.version import Version as Version
from frappe.core.doctype.view_log.view_log import ViewLog as ViewLog
from frappe.custom.doctype.client_script.client_script import ClientScript as ClientScript
from frappe.custom.doctype.custom_field.custom_field import CustomField as CustomField
from frappe.custom.doctype.customize_form.customize_form import CustomizeForm as CustomizeForm
from frappe.custom.doctype.customize_form_field.customize_form_field import (
	CustomizeFormField as CustomizeFormField,
)
from frappe.custom.doctype.doctype_layout.doctype_layout import DocTypeLayout as DocTypeLayout
from frappe.custom.doctype.doctype_layout_field.doctype_layout_field import (
	DocTypeLayoutField as DocTypeLayoutField,
)
from frappe.custom.doctype.property_setter.property_setter import PropertySetter as PropertySetter
from frappe.desk.doctype.bulk_update.bulk_update import BulkUpdate as BulkUpdate
from frappe.desk.doctype.calendar_view.calendar_view import CalendarView as CalendarView
from frappe.desk.doctype.changelog_feed.changelog_feed import ChangelogFeed as ChangelogFeed
from frappe.desk.doctype.console_log.console_log import ConsoleLog as ConsoleLog
from frappe.desk.doctype.custom_html_block.custom_html_block import CustomHTMLBlock as CustomHTMLBlock
from frappe.desk.doctype.dashboard.dashboard import Dashboard as Dashboard
from frappe.desk.doctype.dashboard_chart.dashboard_chart import DashboardChart as DashboardChart
from frappe.desk.doctype.dashboard_chart_field.dashboard_chart_field import (
	DashboardChartField as DashboardChartField,
)
from frappe.desk.doctype.dashboard_chart_link.dashboard_chart_link import (
	DashboardChartLink as DashboardChartLink,
)
from frappe.desk.doctype.dashboard_chart_source.dashboard_chart_source import (
	DashboardChartSource as DashboardChartSource,
)
from frappe.desk.doctype.dashboard_settings.dashboard_settings import DashboardSettings as DashboardSettings
from frappe.desk.doctype.desktop_icon.desktop_icon import DesktopIcon as DesktopIcon
from frappe.desk.doctype.desktop_layout.desktop_layout import DesktopLayout as DesktopLayout
from frappe.desk.doctype.desktop_settings.desktop_settings import DesktopSettings as DesktopSettings
from frappe.desk.doctype.event.event import Event as Event
from frappe.desk.doctype.event_notifications.event_notifications import (
	EventNotifications as EventNotifications,
)
from frappe.desk.doctype.event_participants.event_participants import EventParticipants as EventParticipants
from frappe.desk.doctype.form_tour.form_tour import FormTour as FormTour
from frappe.desk.doctype.form_tour_step.form_tour_step import FormTourStep as FormTourStep
from frappe.desk.doctype.global_search_doctype.global_search_doctype import (
	GlobalSearchDocType as GlobalSearchDocType,
)
from frappe.desk.doctype.global_search_settings.global_search_settings import (
	GlobalSearchSettings as GlobalSearchSettings,
)
from frappe.desk.doctype.kanban_board.kanban_board import KanbanBoard as KanbanBoard
from frappe.desk.doctype.kanban_board_column.kanban_board_column import KanbanBoardColumn as KanbanBoardColumn
from frappe.desk.doctype.list_filter.list_filter import ListFilter as ListFilter
from frappe.desk.doctype.list_view_settings.list_view_settings import ListViewSettings as ListViewSettings
from frappe.desk.doctype.module_onboarding.module_onboarding import ModuleOnboarding as ModuleOnboarding
from frappe.desk.doctype.note.note import Note as Note
from frappe.desk.doctype.note_seen_by.note_seen_by import NoteSeenBy as NoteSeenBy
from frappe.desk.doctype.notification_log.notification_log import NotificationLog as NotificationLog
from frappe.desk.doctype.notification_settings.notification_settings import (
	NotificationSettings as NotificationSettings,
)
from frappe.desk.doctype.notification_subscribed_document.notification_subscribed_document import (
	NotificationSubscribedDocument as NotificationSubscribedDocument,
)
from frappe.desk.doctype.number_card.number_card import NumberCard as NumberCard
from frappe.desk.doctype.number_card_link.number_card_link import NumberCardLink as NumberCardLink
from frappe.desk.doctype.onboarding_permission.onboarding_permission import (
	OnboardingPermission as OnboardingPermission,
)
from frappe.desk.doctype.onboarding_step.onboarding_step import OnboardingStep as OnboardingStep
from frappe.desk.doctype.onboarding_step_map.onboarding_step_map import OnboardingStepMap as OnboardingStepMap
from frappe.desk.doctype.route_history.route_history import RouteHistory as RouteHistory
from frappe.desk.doctype.sidebar_item_group.sidebar_item_group import SidebarItemGroup as SidebarItemGroup
from frappe.desk.doctype.sidebar_item_group_link.sidebar_item_group_link import (
	SidebarItemGroupLink as SidebarItemGroupLink,
)
from frappe.desk.doctype.system_console.system_console import SystemConsole as SystemConsole
from frappe.desk.doctype.system_health_report.system_health_report import (
	SystemHealthReport as SystemHealthReport,
)
from frappe.desk.doctype.system_health_report_errors.system_health_report_errors import (
	SystemHealthReportErrors as SystemHealthReportErrors,
)
from frappe.desk.doctype.system_health_report_failing_jobs.system_health_report_failing_jobs import (
	SystemHealthReportFailingJobs as SystemHealthReportFailingJobs,
)
from frappe.desk.doctype.system_health_report_queue.system_health_report_queue import (
	SystemHealthReportQueue as SystemHealthReportQueue,
)
from frappe.desk.doctype.system_health_report_tables.system_health_report_tables import (
	SystemHealthReportTables as SystemHealthReportTables,
)
from frappe.desk.doctype.system_health_report_workers.system_health_report_workers import (
	SystemHealthReportWorkers as SystemHealthReportWorkers,
)
from frappe.desk.doctype.tag.tag import Tag as Tag
from frappe.desk.doctype.tag_link.tag_link import TagLink as TagLink
from frappe.desk.doctype.todo.todo import ToDo as ToDo
from frappe.desk.doctype.workspace.workspace import Workspace as Workspace
from frappe.desk.doctype.workspace_chart.workspace_chart import WorkspaceChart as WorkspaceChart
from frappe.desk.doctype.workspace_custom_block.workspace_custom_block import (
	WorkspaceCustomBlock as WorkspaceCustomBlock,
)
from frappe.desk.doctype.workspace_link.workspace_link import WorkspaceLink as WorkspaceLink
from frappe.desk.doctype.workspace_number_card.workspace_number_card import (
	WorkspaceNumberCard as WorkspaceNumberCard,
)
from frappe.desk.doctype.workspace_quick_list.workspace_quick_list import (
	WorkspaceQuickList as WorkspaceQuickList,
)
from frappe.desk.doctype.workspace_shortcut.workspace_shortcut import WorkspaceShortcut as WorkspaceShortcut
from frappe.desk.doctype.workspace_sidebar.workspace_sidebar import WorkspaceSidebar as WorkspaceSidebar
from frappe.desk.doctype.workspace_sidebar_item.workspace_sidebar_item import (
	WorkspaceSidebarItem as WorkspaceSidebarItem,
)
from frappe.email.doctype.auto_email_report.auto_email_report import AutoEmailReport as AutoEmailReport
from frappe.email.doctype.document_follow.document_follow import DocumentFollow as DocumentFollow
from frappe.email.doctype.email_account.email_account import EmailAccount as EmailAccount
from frappe.email.doctype.email_domain.email_domain import EmailDomain as EmailDomain
from frappe.email.doctype.email_flag_queue.email_flag_queue import EmailFlagQueue as EmailFlagQueue
from frappe.email.doctype.email_group.email_group import EmailGroup as EmailGroup
from frappe.email.doctype.email_group_member.email_group_member import EmailGroupMember as EmailGroupMember
from frappe.email.doctype.email_queue.email_queue import EmailQueue as EmailQueue
from frappe.email.doctype.email_queue_recipient.email_queue_recipient import (
	EmailQueueRecipient as EmailQueueRecipient,
)
from frappe.email.doctype.email_rule.email_rule import EmailRule as EmailRule
from frappe.email.doctype.email_template.email_template import EmailTemplate as EmailTemplate
from frappe.email.doctype.email_unsubscribe.email_unsubscribe import EmailUnsubscribe as EmailUnsubscribe
from frappe.email.doctype.imap_folder.imap_folder import IMAPFolder as IMAPFolder
from frappe.email.doctype.notification.notification import Notification as Notification
from frappe.email.doctype.notification_recipient.notification_recipient import (
	NotificationRecipient as NotificationRecipient,
)
from frappe.email.doctype.reply_to_address.reply_to_address import ReplyToAddress as ReplyToAddress
from frappe.email.doctype.unhandled_email.unhandled_email import UnhandledEmail as UnhandledEmail
from frappe.geo.doctype.country.country import Country as Country
from frappe.geo.doctype.currency.currency import Currency as Currency
from frappe.integrations.doctype.connected_app.connected_app import ConnectedApp as ConnectedApp
from frappe.integrations.doctype.geolocation_settings.geolocation_settings import (
	GeolocationSettings as GeolocationSettings,
)
from frappe.integrations.doctype.google_calendar.google_calendar import GoogleCalendar as GoogleCalendar
from frappe.integrations.doctype.google_contacts.google_contacts import GoogleContacts as GoogleContacts
from frappe.integrations.doctype.google_settings.google_settings import GoogleSettings as GoogleSettings
from frappe.integrations.doctype.integration_request.integration_request import (
	IntegrationRequest as IntegrationRequest,
)
from frappe.integrations.doctype.ldap_group_mapping.ldap_group_mapping import (
	LDAPGroupMapping as LDAPGroupMapping,
)
from frappe.integrations.doctype.ldap_settings.ldap_settings import LDAPSettings as LDAPSettings
from frappe.integrations.doctype.oauth_authorization_code.oauth_authorization_code import (
	OAuthAuthorizationCode as OAuthAuthorizationCode,
)
from frappe.integrations.doctype.oauth_bearer_token.oauth_bearer_token import (
	OAuthBearerToken as OAuthBearerToken,
)
from frappe.integrations.doctype.oauth_client.oauth_client import OAuthClient as OAuthClient
from frappe.integrations.doctype.oauth_client_role.oauth_client_role import OAuthClientRole as OAuthClientRole
from frappe.integrations.doctype.oauth_provider_settings.oauth_provider_settings import (
	OAuthProviderSettings as OAuthProviderSettings,
)
from frappe.integrations.doctype.oauth_scope.oauth_scope import OAuthScope as OAuthScope
from frappe.integrations.doctype.oauth_settings.oauth_settings import OAuthSettings as OAuthSettings
from frappe.integrations.doctype.push_notification_settings.push_notification_settings import (
	PushNotificationSettings as PushNotificationSettings,
)
from frappe.integrations.doctype.query_parameters.query_parameters import QueryParameters as QueryParameters
from frappe.integrations.doctype.slack_webhook_url.slack_webhook_url import SlackWebhookURL as SlackWebhookURL
from frappe.integrations.doctype.social_login_key.social_login_key import SocialLoginKey as SocialLoginKey
from frappe.integrations.doctype.token_cache.token_cache import TokenCache as TokenCache
from frappe.integrations.doctype.webhook.webhook import Webhook as Webhook
from frappe.integrations.doctype.webhook_data.webhook_data import WebhookData as WebhookData
from frappe.integrations.doctype.webhook_header.webhook_header import WebhookHeader as WebhookHeader
from frappe.integrations.doctype.webhook_request_log.webhook_request_log import (
	WebhookRequestLog as WebhookRequestLog,
)
from frappe.printing.doctype.letter_head.letter_head import LetterHead as LetterHead
from frappe.printing.doctype.network_printer_settings.network_printer_settings import (
	NetworkPrinterSettings as NetworkPrinterSettings,
)
from frappe.printing.doctype.print_format.print_format import PrintFormat as PrintFormat
from frappe.printing.doctype.print_format_field_template.print_format_field_template import (
	PrintFormatFieldTemplate as PrintFormatFieldTemplate,
)
from frappe.printing.doctype.print_heading.print_heading import PrintHeading as PrintHeading
from frappe.printing.doctype.print_settings.print_settings import PrintSettings as PrintSettings
from frappe.printing.doctype.print_style.print_style import PrintStyle as PrintStyle
from frappe.website.doctype.about_us_settings.about_us_settings import AboutUsSettings as AboutUsSettings
from frappe.website.doctype.about_us_team_member.about_us_team_member import (
	AboutUsTeamMember as AboutUsTeamMember,
)
from frappe.website.doctype.color.color import Color as Color
from frappe.website.doctype.company_history.company_history import CompanyHistory as CompanyHistory
from frappe.website.doctype.contact_us_settings.contact_us_settings import (
	ContactUsSettings as ContactUsSettings,
)
from frappe.website.doctype.discussion_reply.discussion_reply import DiscussionReply as DiscussionReply
from frappe.website.doctype.discussion_topic.discussion_topic import DiscussionTopic as DiscussionTopic
from frappe.website.doctype.help_article.help_article import HelpArticle as HelpArticle
from frappe.website.doctype.help_category.help_category import HelpCategory as HelpCategory
from frappe.website.doctype.personal_data_deletion_request.personal_data_deletion_request import (
	PersonalDataDeletionRequest as PersonalDataDeletionRequest,
)
from frappe.website.doctype.personal_data_deletion_step.personal_data_deletion_step import (
	PersonalDataDeletionStep as PersonalDataDeletionStep,
)
from frappe.website.doctype.personal_data_download_request.personal_data_download_request import (
	PersonalDataDownloadRequest as PersonalDataDownloadRequest,
)
from frappe.website.doctype.portal_menu_item.portal_menu_item import PortalMenuItem as PortalMenuItem
from frappe.website.doctype.portal_settings.portal_settings import PortalSettings as PortalSettings
from frappe.website.doctype.social_link_settings.social_link_settings import (
	SocialLinkSettings as SocialLinkSettings,
)
from frappe.website.doctype.top_bar_item.top_bar_item import TopBarItem as TopBarItem
from frappe.website.doctype.utm_campaign.utm_campaign import UTMCampaign as UTMCampaign
from frappe.website.doctype.utm_medium.utm_medium import UTMMedium as UTMMedium
from frappe.website.doctype.utm_source.utm_source import UTMSource as UTMSource
from frappe.website.doctype.web_form.web_form import WebForm as WebForm
from frappe.website.doctype.web_form_field.web_form_field import WebFormField as WebFormField
from frappe.website.doctype.web_form_list_column.web_form_list_column import (
	WebFormListColumn as WebFormListColumn,
)
from frappe.website.doctype.web_page.web_page import WebPage as WebPage
from frappe.website.doctype.web_page_block.web_page_block import WebPageBlock as WebPageBlock
from frappe.website.doctype.web_page_view.web_page_view import WebPageView as WebPageView
from frappe.website.doctype.web_template.web_template import WebTemplate as WebTemplate
from frappe.website.doctype.web_template_field.web_template_field import WebTemplateField as WebTemplateField
from frappe.website.doctype.website_meta_tag.website_meta_tag import WebsiteMetaTag as WebsiteMetaTag
from frappe.website.doctype.website_route_meta.website_route_meta import WebsiteRouteMeta as WebsiteRouteMeta
from frappe.website.doctype.website_route_redirect.website_route_redirect import (
	WebsiteRouteRedirect as WebsiteRouteRedirect,
)
from frappe.website.doctype.website_script.website_script import WebsiteScript as WebsiteScript
from frappe.website.doctype.website_settings.website_settings import WebsiteSettings as WebsiteSettings
from frappe.website.doctype.website_sidebar.website_sidebar import WebsiteSidebar as WebsiteSidebar
from frappe.website.doctype.website_sidebar_item.website_sidebar_item import (
	WebsiteSidebarItem as WebsiteSidebarItem,
)
from frappe.website.doctype.website_slideshow.website_slideshow import WebsiteSlideshow as WebsiteSlideshow
from frappe.website.doctype.website_slideshow_item.website_slideshow_item import (
	WebsiteSlideshowItem as WebsiteSlideshowItem,
)
from frappe.website.doctype.website_theme.website_theme import WebsiteTheme as WebsiteTheme
from frappe.website.doctype.website_theme_ignore_app.website_theme_ignore_app import (
	WebsiteThemeIgnoreApp as WebsiteThemeIgnoreApp,
)
from frappe.workflow.doctype.workflow.workflow import Workflow as Workflow
from frappe.workflow.doctype.workflow_action.workflow_action import WorkflowAction as WorkflowAction
from frappe.workflow.doctype.workflow_action_master.workflow_action_master import (
	WorkflowActionMaster as WorkflowActionMaster,
)
from frappe.workflow.doctype.workflow_action_permitted_role.workflow_action_permitted_role import (
	WorkflowActionPermittedRole as WorkflowActionPermittedRole,
)
from frappe.workflow.doctype.workflow_document_state.workflow_document_state import (
	WorkflowDocumentState as WorkflowDocumentState,
)
from frappe.workflow.doctype.workflow_state.workflow_state import WorkflowState as WorkflowState
from frappe.workflow.doctype.workflow_transition.workflow_transition import (
	WorkflowTransition as WorkflowTransition,
)
from frappe.workflow.doctype.workflow_transition_task.workflow_transition_task import (
	WorkflowTransitionTask as WorkflowTransitionTask,
)
from frappe.workflow.doctype.workflow_transition_tasks.workflow_transition_tasks import (
	WorkflowTransitionTasks as WorkflowTransitionTasks,
)
