name: Downstream

on:
  workflow_dispatch:

jobs:
  dispatch:
    strategy:
      matrix:
        repo:
          - frappe/erpnext
          - frappe/lending
          - frappe/hrms
    steps:
      - name: Dispatch Downstream CI (if supported)
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.CI_PAT }}
          repository: ${{ matrix.repo }}
          event-type: frappe-framework-change
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
