name: Regenerate POT file (translatable strings)
on:
  schedule:
    # 9:30 UTC => 3 PM IST Sunday
    - cron: "30 9 * * 0"
  workflow_dispatch:

jobs:
  regenerate-pot-file:
    name: Regenerate POT file
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - branch: "develop"
            python: "3.14"
          - branch: "version-16-hotfix"
            python: "3.14"
          - branch: "version-15-hotfix"
            python: "3.10"
    permissions:
      contents: write

    steps:
        - name: Checkout
          uses: actions/checkout@v7
          with:
            ref: ${{ matrix.branch }}

        - name: Setup Python
          uses: actions/setup-python@v7
          with:
            python-version: ${{ matrix.python }}

        - name: Setup Node
          uses: actions/setup-node@v7
          with:
            node-version: 24

        - name: Run script to update POT file
          run: |
            bash ${GITHUB_WORKSPACE}/.github/helper/update_pot_file.sh
          env:
            GH_TOKEN: ${{ secrets.RELEASE_TOKEN }}
            BASE_BRANCH: ${{ matrix.branch }}
